### ISSUE TITLE
Clarify usage: does this work with a StatefulSet?

### ISSUE THREAD

**Issue by ivanbrennan** [arturictus/sidekiq_alive#11]
Apologies if this a stupid question, but I'm trying to figure out if this project is specifically for Sidekiq running as a kubernetes Deployment, or whether it would also work if you're running Sidekiq as a StatefulSet.

Partly, I'm trying to figure out whether it makes more sense to run as one or the other.

**Comment by arturictus** [comment]
Hi @ivanbrennan,
This library can work even in a single server. If you'll like to check if sidekiq is processing you can just pin to the port specified in the config.

For what I see, statefulSets are more suited for Databases, repositories or applications that require a storage volume. Sidekiq is a stateless application, Redis handles the state. I do not see why you will want to do it in statefulSet. Deployments allow you to scale easily and that's what you want for Sidekiq.
Unless your workers write on disk I do not see why you should do statefulSet.

About your question:
If stateFulSets have a livenessProve you can use the gem.

**Comment by ivanbrennan** [comment]
@arturictus Thanks!
