### ISSUE TITLE
Queue is not removed when sidekiq stops

### ISSUE THREAD

**Issue by arturictus** [arturictus/sidekiq_alive#25]
![Screenshot from 2019-10-07 15-36-45](https://user-images.githubusercontent.com/1930175/66316696-70a72580-e918-11e9-884c-2356e667b4bc.png)

**Comment by sunny** [comment]
I am currently doing this daily to deal with this issue:

```rb
Sidekiq::Queue
  .all
  .select { |q| q.name =~ /^sidekiq_alive-/ }
  .select { |q| q.any? { |w| w.created_at < 1.day.ago } }
  .each(&:clear)
```

Obviously not ideal, but helps for the time being.
