### ISSUE TITLE
Sinatra not using the port from a Sidekiq.setup block

### ISSUE THREAD

**Issue by bcantin** [arturictus/sidekiq_alive#27]
https://github.com/arturictus/sidekiq_alive/pull/26 addresses this issue.

I found that when I was using the sidekiq_alive_example rails application and I changed the port in the config/sidekiq_alive.rb file, it was being set for the SidekiqAlive singleton, but the Sinatra application was not loading it properly.

The given PR adds tests and an updated lib/sidekiq_alive/server.rb to load the port.

Thank you

**Comment by arturictus** [comment]
released fix on version 2.0.1
