### ISSUE TITLE
Change queue name?

### ISSUE THREAD

**Issue by iainbryson** [arturictus/sidekiq_alive#33]
I'm curious about why each host gets its own queue.  As I understand it, Sidekiq recommends as few queues as possible.  If I want to put the alives in my `critical`, what problem does that cause?

I suppose I can monkey-patch the name, but it seems like this is an 'obvious' feature, so maybe I'm missing some bad implications of doing so.

**Comment by arturictus** [comment]
Each replica | instance has to check it's own status.
example: 
- Instance 1
- instance 2
The only way to know if instance 1 is processing jobs it's by instance 1 to process the job.

If you have a single queue you have to requeue the job until it gets processed by the referencing instance.
Previous versions used a single queue approach and were causing a lot of load to redis and very random behavior.
https://github.com/arturictus/sidekiq_alive/issues/10

I hope that clarifies why each instance has its own queue.
