### ISSUE TITLE
Change log format or remove health logs.

### ISSUE THREAD

**Issue by MFProduction** [arturictus/sidekiq_alive#44]
Hi, is it possible te remove health logs or change format?

**Comment by maltesa** [comment]
yes, that would be great. The health checks are polluting my worker logs. Also, webrick is not using my json logger.

**Comment by arturictus** [comment]
Hi @MFProduction and @maltesa,
Any idea of how to implement it?

**Comment by maltesa** [comment]
This works for me: https://github.com/arturictus/sidekiq_alive/pull/49
This disables logs when using webrick. Puma seems to log nothing by default.

**Comment by AgrimPrasad** [comment]
Yes please. This is very spammy for us and is driving up log storage costs. @arturictus could we please get #49 in? Thanks!

**Comment by arturictus** [comment]
Hi @maltesa and @AgrimPrasad , 
I released version **2.1.0** which contains #49 .
Thanks for the PR and testing it
