### ISSUE TITLE
Question: why grep busy in graceful shutdown

### ISSUE THREAD

**Issue by flovilmart** [arturictus/sidekiq_alive#47]
Hi! Thanks for maintaining this project.

When integrating, one of my coworkers came with this question:

```
#!/bin/bash

# Find Pid
SIDEKIQ_PID=$(ps aux | grep sidekiq | grep busy | awk '{ print $2 }')
```

Why grep busy? Could this possibly not match sometimes? If so, would need to be handled below

Any chance you can clarify for us the need for `busy`?

thanks!

**Comment by arturictus** [comment]
Hi @flovilmart,
Thanks for pointing out.
This code is an example script to find the PID managing the sidekiq process, the `busy` is a way to select the right one.
If you have a better way I'm happy to change the docs, even add it into the lib.
Here is my output in console:
![image](https://user-images.githubusercontent.com/1930175/112827683-95500980-9086-11eb-90e4-aed114b3e372.png)

**Comment by flovilmart** [comment]
Gotcha! Thanks for the explanation.
