### ISSUE TITLE
Add webrick as a dependency for Ruby 3

### ISSUE THREAD

**Issue by matthieu-foucault** [arturictus/sidekiq_alive#56]
As of Ruby 3.0.0, webrick is no longer part of the standard library: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

The default server for this project is `webrick`, so it should be added as a dependency in the gemspec file

**Comment by BrianSigafoos** [comment]
Or please at least add a note for Ruby 3.0+ to add `webrick` as a dependency OR change the config's default to `puma`, etc. 🙏

**Comment by arturictus** [comment]
Hi @matthieu-foucault, thanks for pointing out this issue. 
This #51 solves this and it is released at `2.1.4`.s

Hi @BrianSigafoos, You have a config to change the server, I'm happy to accept PRs or discussions to move to `puma`.
