### ISSUE TITLE
Increasing SidekiqAlive workers

### ISSUE THREAD

**Issue by linyaoli** [arturictus/sidekiq_alive#6]
![screen shot 2018-08-30 at 5 14 20 pm](https://user-images.githubusercontent.com/1335416/44842373-39c40200-ac78-11e8-99c3-1bf485029244.png)
![screen shot 2018-08-30 at 5 14 28 pm](https://user-images.githubusercontent.com/1335416/44842374-3a5c9880-ac78-11e8-9a2d-9eccd5e2acdd.png)

Hi, I've started to use SidekiqAlive for k8s liveness probing since last week and noticed the workers are piling up. Is this expected? Shouldn't the older ones be removed automatically?

Thanks in advance.

**Comment by linyaoli** [comment]
ping @arturictus in case you missed this.

**Comment by arturictus** [comment]
Hi @linyaoli ,
This is not intended.
I'm about to release a new version solving many issues #5. Is still in development. I hope I can release it soon.
Thanks for the feedback!

**Comment by arturictus** [comment]
@linyaoli , new version released. check it out!.
Thanks for the feedback

**Comment by linyaoli** [comment]
Great! I'll test it this week.
