### ISSUE TITLE
`RedisClient::CannotConnectError: stream closed in another thread` after updates

### ISSUE THREAD

**Issue by fwolfst** [arturictus/sidekiq_alive#89]
Thanks for the work on sidekiq-alive.
After a recent update (to 2.2 and sidekiq 7.1), I see following errors on a multi-instance installation regularly (not reproducible, 1-x times per day under no load).
There is no further information on the Job itself (its in the proper instance-specific queue, and of class `SidekiqAlive::Worker`.

![image](https://user-images.githubusercontent.com/219373/236122057-0ae8a920-2ea1-46fc-a783-72809cfadf6b.png)

How can we further debug this?

**Comment by WoutDev** [comment]
I see a similar error in my death handler. It seems to (timewise) roughly match a k8s rolling update on my Sidekiq pod. I only have a single pod running though.

**Comment by arturictus** [comment]
Thanks, @juanbandajr.
@fwolfst checking the Sidekiq code makes all the sense to run the commands inside the block.
https://github.com/sidekiq/sidekiq/blob/0175cdbe03c3a9edf908a155ae6f006061b5c224/lib/sidekiq/config.rb#L155-L174
Would you like to make a PR?

**Comment by fwolfst** [comment]
> Thanks, @juanbandajr. @fwolfst checking the Sidekiq code makes all the sense to run the commands inside the block. https://github.com/sidekiq/sidekiq/blob/0175cdbe03c3a9edf908a155ae6f006061b5c224/lib/sidekiq/config.rb#L155-L174 Would you like to make a PR?

Sorry, too late ... :)

**Comment by arturictus** [comment]
solved
